using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GDUTSharp.SourceGen.Generators
{
    [Generator]
    public class Gen_OverrideToString : IIncrementalGenerator
    {
        private static readonly string _attributeFullName = "GDUTSharp.Shared.Attributes.OverrideToString";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName
                (
                    _attributeFullName,
                    static (node, token) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                    (GeneratorAttributeSyntaxContext syntaxContext, CancellationToken token) => GetTypeToGenerate(syntaxContext)
                ).Where(static m => m is not null);
            context.RegisterSourceOutput(provider, static (spc, typeInfo) =>
                ExecuteGeneration(spc, typeInfo));
        }

        private class TypeToGenerate(
            string nameSpace,
            string typeName,
            TypeKind typeKind,
            ImmutableArray<(string Name, string Type)> propertyInfos,
            string? displayName = null)
        {
            public string Namespace { get; set; } = nameSpace;
            public string TypeName { get; set; } = typeName;
            public string TypeKind { get; set; } = typeKind switch
            {
                Microsoft.CodeAnalysis.TypeKind.Class => "class",
                Microsoft.CodeAnalysis.TypeKind.Struct => "struct",
                _ => throw new InvalidDataException()
            };
            public ImmutableArray<(string Name, string Type)> PropertyInfos { get; set; } = propertyInfos;
            public string DisplayName { get; set; } = displayName ?? typeName;
        }

        private static TypeToGenerate? GetTypeToGenerate(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
            var properties = typeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .Select(p => (p.Name, p.Type.ToDisplayString()))
                .ToImmutableArray();
            return new TypeToGenerate(
                typeSymbol.ContainingNamespace.ToDisplayString(),
                typeSymbol.Name,
                typeSymbol.TypeKind,
                properties);
        }

        private static void ExecuteGeneration(SourceProductionContext context, TypeToGenerate? typeInfo)
        {
            if (typeInfo is null) return;
            var sb = new StringBuilder();
            sb.AppendLine($"            {typeInfo.DisplayName}:");
            for (int i = 0; i < typeInfo.PropertyInfos.Length; i++)
            {
                var (Name, _) = typeInfo.PropertyInfos[i];
                sb.AppendLine($"              - {Name}:{{{Name}}}");
            }
            var content = sb.ToString();
            sb.Clear();
            sb.AppendLine($$""""
                // <auto-generated/>
                namespace {{typeInfo.Namespace}}
                {
                    partial {{typeInfo.TypeKind}} {{typeInfo.TypeName}}
                    {
                        /// <summary>由 GDUTSharp.SourceGen 自动覆写</summary>
                        public override string ToString() {
                            return $"""
                {{content}}
                            """;
                        }
                    }
                }
                """");
            context.AddSource($"{typeInfo.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
